# Generated by Django 3.2.13 on 2022-04-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Criteria",
        ),
    ]
